[#43] 스트리밍 서비스 확장
SmashStudy/ESquad-serverless-monorepo pull request #100
Opened 2024-11-30 16:25 UTC by andle7

https://github.com/SmashStudy/ESquad-serverless-monorepo/issues/43

2024-11-30 16:39 UTC, kimmin1kk requested changes
고생하셨습니다 리뷰 확인해주세요!

2024-11-30 16:39 UTC, kimmin1kk commented on frontend/src/pages/stream/LiveStreamWindow.jsx
> +    const popupUrl = `https://localhost:9000/?studyId=${studyId}&name=${encodeURIComponent(nickname)}`;
수정이 필요한 부분 같아보입니다!

2024-11-30 16:39 UTC, kimmin1kk commented on frontend/src/pages/team/study/StudyListPage.jsx
> +      // 에러 처리 로직을 추가하세요.
이런 주석들은 제거해주셔도 좋을 거 같아요!

2024-11-30 16:39 UTC, kimmin1kk commented on frontend/src/pages/team/study/StudyListPage.jsx
> +              Button
Received `true` for a non-boolean attribute `button` 오류 해결을 위해 추가하신건가요??
근데 Button으로 수정하고 로컬에서 해당 부분 돌려보니 React does not recognize the `Button` prop on a DOM element가 뜨는데 따로 처리되는 부분이 있는건지 궁금합니다!

2024-11-30 16:41 UTC, andle7 commented on frontend/src/pages/stream/LiveStreamWindow.jsx
> +    const popupUrl = `https://localhost:9000/?studyId=${studyId}&name=${encodeURIComponent(nickname)}`;
넵 다시 수정했습니다! 감사합니다!

2024-12-01 04:04 UTC, yejeii approved these changes

2024-12-01 11:38 UTC, kimmin1kk reviewed
리뷰 확인해주시면 감사하겠습니다!

2024-12-01 11:38 UTC, kimmin1kk commented on frontend/src/pages/stream/LiveStreamWindow.jsx
> +    const popupUrl = `https://live.dev.esquad.click/?studyId=${studyId}&name=${encodeURIComponent(nickname)}`;
이 부분은 apiConfig로 관리를 안하고 따로 넣어둔 이유가 있는건지 궁금합니다!

2024-12-01 12:05 UTC, andle7 commented on frontend/src/pages/stream/LiveStreamWindow.jsx
> +    const popupUrl = `https://live.dev.esquad.click/?studyId=${studyId}&name=${encodeURIComponent(nickname)}`;
넵 local, dev 주소 분리되도록 반영했습니다!
감사합니다!

2024-12-01 16:14 UTC, kimmin1kk approved these changes

2024-12-01 16:15 UTC, merged