Feature/24
SmashStudy/ESquad-serverless-monorepo pull request #71
Opened 2024-11-26 10:05 UTC by wive10

2024-11-26 17:38 UTC, kimmin1kk requested changes
한 수 배우고 갑니다.. 리뷰 확인하고 피드백 부탁드립니다! 😃

2024-11-27 06:25 UTC, wive10 commented on frontend/src/components/header/SidebarComponent.jsx
> +    console.log(selectedTeam);
확인하였습니다!

2024-11-27 07:26 UTC, kimmin1kk requested changes
리뷰 확인해주세요~~

2024-11-27 07:26 UTC, kimmin1kk commented on frontend/src/components/header/AppbarComponent.jsx
> +          const response = await axios.get('https://api.esquad.click/local/users/get-nickname', {
/dev 로 바꿔주세용

2024-12-02 02:20 UTC, andle7 commented
고생하셨습니다!  😃

2024-12-03 11:15 UTC, merged